easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User

    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png"/>'